import schedule
import time
import json
import os
import threading
from rich.console import Console

console = Console()

SCHEDULE_FILE = "schedules.json"

class SchedulerService:
    """
    Manages daily automated tasks.
    Persistence: schedules.json
    """
    def __init__(self, creds):
        self.creds = creds
        self.running = False
        self.jobs = []
        self.load_schedules()

    def load_schedules(self):
        """Loads saved schedules from JSON."""
        if os.path.exists(SCHEDULE_FILE):
            try:
                with open(SCHEDULE_FILE, 'r') as f:
                    self.jobs = json.load(f)
            except:
                self.jobs = []

    def save_schedules(self):
        """Saves current jobs to JSON."""
        with open(SCHEDULE_FILE, 'w') as f:
            json.dump(self.jobs, f, indent=4)

    def add_daily_email_summary(self, time_str):
        """
        Schedules a daily email summary job.
        """
        # Validate time format HH:MM
        try:
            time.strptime(time_str, '%H:%M')
        except ValueError:
            console.print("[red]Invalid time format. Use HH:MM in 24h format.[/red]")
            return False

        job = {
            "type": "email_summary",
            "time": time_str,
            "active": True
        }
        
        self.jobs.append(job)
        self.save_schedules()
        console.print(f"[green]Daily Email Digest scheduled for {time_str}![/green]")
        return True

    def run_pending(self):
        """
        Entry point to run scheduler loop. 
        In a real CLI, this would run in a background daemon or service.
        For this demo, we simulate checking.
        """
        # Re-register jobs (simplified)
        schedule.clear()
        
        for job in self.jobs:
            if job['type'] == 'email_summary' and job['active']:
                schedule.every().day.at(job['time']).do(self.send_daily_digest)
        
        console.print(f"[yellow]Scheduler active with {len(self.jobs)} jobs. Press Ctrl+C to stop.[/yellow]")
        
        self.running = True
        try:
            while self.running:
                schedule.run_pending()
                time.sleep(1)
        except KeyboardInterrupt:
            console.print("\n[yellow]Scheduler stopped.[/yellow]")

    def send_daily_digest(self):
        """
        The actual job logic: Fetch emails, summarize, send via Gmail API.
        """
        from services.gmail import GmailService
        console.print(f"[bold magenta]⏰ Running Scheduled Job: Daily Email Digest[/bold magenta]")
        
        try:
            gmail = GmailService(self.creds)
            messages = gmail.list_messages(max_results=5)
            
            if not messages:
                console.print("No new emails to summarize.")
                return

            # Simulate summarization
            summary_body = "Daily Digest:\n\n"
            for m in messages:
                summary_body += f"- {m['Subject']} (From: {m['From']})\n"
            
            summary_body += "\n(Generated by Terminus AI)"
            
            # Send Email (Using Gmail API 'send' - implementation stub)
            # real implementation would require constructing MIME message
            console.print(f"[green]Sending Digest to user...[/green]")
            console.print(summary_body)
            # gmail.send_email("me", "Daily Update", summary_body) # Future implementation
            
        except Exception as e:
             console.print(f"[red]Job Failed: {e}[/red]")
